{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 745, "y": 307}, "vk": "default", "time": 1605664149.110789}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 749, "y": 307}, "vk": "default", "time": 1605664149.110789}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 750, "y": 307}, "vk": "default", "time": 1605664149.1137187}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 751, "y": 308}, "vk": "default", "time": 1605664149.1273906}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 752, "y": 308}, "vk": "default", "time": 1605664149.148875}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 752, "y": 309}, "vk": "default", "time": 1605664149.160594}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 752, "y": 310}, "vk": "default", "time": 1605664149.1723125}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 753, "y": 310}, "vk": "default", "time": 1605664149.3461406}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 753, "y": 309}, "vk": "default", "time": 1605664149.501414}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 754, "y": 309}, "vk": "default", "time": 1605664149.566844}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 755, "y": 306}, "vk": "default", "time": 1605664149.6039531}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 756, "y": 305}, "vk": "default", "time": 1605664149.6156719}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 756, "y": 304}, "vk": "default", "time": 1605664149.7172344}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 756, "y": 304}, "vk": "default", "time": 1605664150.566844}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 756, "y": 304}, "vk": "default", "time": 1605664150.5678203}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 756, "y": 304}, "vk": "default", "time": 1605664150.7728987}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 756, "y": 304}, "vk": "default", "time": 1605664150.7728987}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 755, "y": 304}, "vk": "default", "time": 1605664157.4984844}
