{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.116781}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.6168094}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.6468115}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.6868136}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.7168155}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.746817}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.7768188}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.816821}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.847823}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.8778245}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989809.917827}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 67, "time": 1594989810.0288334}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 67, "time": 1594989810.1518402}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989810.1918426}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989810.9618864}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989811.4629152}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 67, "time": 1594989811.4829164}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 67, "time": 1594989811.6229243}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594989811.6529262}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 27, "time": 1594989813.2050147}
