{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1252, "y": 734}, "vk": "default", "time": 1595202060.8445814}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1252, "y": 734}, "vk": "default", "time": 1595202060.8605824}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1251, "y": 734}, "vk": "default", "time": 1595202060.9325864}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 1251, "y": 734}, "vk": "default", "time": 1595202061.0845952}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 1251, "y": 734}, "vk": "default", "time": 1595202061.5486217}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1255, "y": 735}, "vk": "default", "time": 1595202064.6688}
