{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1132, "y": 676}, "vk": "default", "time": 1594996977.8158069}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1132, "y": 676}, "vk": "default", "time": 1594996977.831808}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1132, "y": 677}, "vk": "default", "time": 1594996977.8398085}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1133, "y": 677}, "vk": "default", "time": 1594996977.847809}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1133, "y": 677}, "vk": "default", "time": 1594996977.8638098}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1134, "y": 677}, "vk": "default", "time": 1594996977.8718102}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1134, "y": 678}, "vk": "default", "time": 1594996977.880811}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1135, "y": 678}, "vk": "default", "time": 1594996977.8878114}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1135, "y": 678}, "vk": "default", "time": 1594996977.8958116}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1135, "y": 678}, "vk": "default", "time": 1594996977.9038122}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1136, "y": 679}, "vk": "default", "time": 1594996977.9198132}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1136, "y": 679}, "vk": "default", "time": 1594996977.935814}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1136, "y": 680}, "vk": "default", "time": 1594996977.9918172}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1136, "y": 680}, "vk": "default", "time": 1594996977.9998176}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1136, "y": 680}, "vk": "default", "time": 1594996978.007818}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1133, "y": 680}, "vk": "default", "time": 1594996978.0158186}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1128, "y": 680}, "vk": "default", "time": 1594996978.023819}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1128, "y": 680}, "vk": "default", "time": 1594996978.0318196}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1125, "y": 680}, "vk": "default", "time": 1594996978.03982}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1124, "y": 680}, "vk": "default", "time": 1594996978.0478203}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1122, "y": 680}, "vk": "default", "time": 1594996978.0558207}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1121, "y": 680}, "vk": "default", "time": 1594996978.0638213}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1118, "y": 680}, "vk": "default", "time": 1594996978.071822}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1115, "y": 680}, "vk": "default", "time": 1594996978.0808222}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1112, "y": 680}, "vk": "default", "time": 1594996978.0878227}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1109, "y": 680}, "vk": "default", "time": 1594996978.095823}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1106, "y": 680}, "vk": "default", "time": 1594996978.1038237}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1106, "y": 680}, "vk": "default", "time": 1594996978.111824}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1103, "y": 680}, "vk": "default", "time": 1594996978.1198244}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1102, "y": 681}, "vk": "default", "time": 1594996978.1358254}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1102, "y": 681}, "vk": "default", "time": 1594996978.1598268}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1102, "y": 681}, "vk": "default", "time": 1594996978.2718332}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1102, "y": 681}, "vk": "default", "time": 1594996978.2808337}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1105, "y": 681}, "vk": "default", "time": 1594996978.2878342}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1108, "y": 681}, "vk": "default", "time": 1594996978.2958345}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1111, "y": 681}, "vk": "default", "time": 1594996978.3038352}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1114, "y": 681}, "vk": "default", "time": 1594996978.3118353}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1117, "y": 681}, "vk": "default", "time": 1594996978.319836}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1120, "y": 682}, "vk": "default", "time": 1594996978.3278365}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1123, "y": 682}, "vk": "default", "time": 1594996978.335837}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1124, "y": 682}, "vk": "default", "time": 1594996978.3438373}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1124, "y": 682}, "vk": "default", "time": 1594996978.3518376}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1127, "y": 682}, "vk": "default", "time": 1594996978.3598382}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1130, "y": 682}, "vk": "default", "time": 1594996978.3838394}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1131, "y": 682}, "vk": "default", "time": 1594996978.3998406}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1131, "y": 682}, "vk": "default", "time": 1594996978.407841}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1132, "y": 682}, "vk": "default", "time": 1594996978.4158416}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1132, "y": 682}, "vk": "default", "time": 1594996978.4238417}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1133, "y": 682}, "vk": "default", "time": 1594996978.4398427}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1134, "y": 682}, "vk": "default", "time": 1594996978.4478433}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1134, "y": 682}, "vk": "default", "time": 1594996978.455844}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1135, "y": 682}, "vk": "default", "time": 1594996978.463844}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1135, "y": 682}, "vk": "default", "time": 1594996978.4808452}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1135, "y": 682}, "vk": "default", "time": 1594996978.4878457}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 1135, "y": 682}, "vk": "default", "time": 1594996979.2398887}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 1135, "y": 682}, "vk": "default", "time": 1594996979.4088984}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 164, "time": 1594996980.4619584}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 91, "time": 1594996980.4619584}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 134, "time": 1594996980.4769595}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 134, "time": 1594996980.5009608}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 164, "time": 1594996980.5169616}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 91, "time": 1594996980.5179617}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 27, "time": 1594996980.8839827}
