{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1553, "y": 471}, "vk": "default", "time": 1594977557.5543845}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1556, "y": 471}, "vk": "default", "time": 1594977557.5623848}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1559, "y": 472}, "vk": "default", "time": 1594977557.5743854}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1561, "y": 472}, "vk": "default", "time": 1594977557.582386}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1564, "y": 472}, "vk": "default", "time": 1594977557.5903864}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1567, "y": 472}, "vk": "default", "time": 1594977557.6023872}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1569, "y": 472}, "vk": "default", "time": 1594977557.6103876}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1571, "y": 472}, "vk": "default", "time": 1594977557.6223881}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1574, "y": 472}, "vk": "default", "time": 1594977557.6303887}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1576, "y": 472}, "vk": "default", "time": 1594977557.638389}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1579, "y": 472}, "vk": "default", "time": 1594977557.6503897}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1581, "y": 472}, "vk": "default", "time": 1594977557.6583903}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1583, "y": 472}, "vk": "default", "time": 1594977557.6703908}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1585, "y": 472}, "vk": "default", "time": 1594977557.6783912}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1587, "y": 472}, "vk": "default", "time": 1594977557.690392}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1587, "y": 472}, "vk": "default", "time": 1594977557.6983926}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1588, "y": 472}, "vk": "default", "time": 1594977557.7103932}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1589, "y": 472}, "vk": "default", "time": 1594977557.7183936}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1590, "y": 472}, "vk": "default", "time": 1594977557.7263942}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1590, "y": 472}, "vk": "default", "time": 1594977557.738395}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1591, "y": 472}, "vk": "default", "time": 1594977557.7463953}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1592, "y": 472}, "vk": "default", "time": 1594977557.7543957}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1593, "y": 472}, "vk": "default", "time": 1594977557.7663965}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1594, "y": 472}, "vk": "default", "time": 1594977557.774397}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1595, "y": 472}, "vk": "default", "time": 1594977557.7863977}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1597, "y": 472}, "vk": "default", "time": 1594977557.794398}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1598, "y": 472}, "vk": "default", "time": 1594977557.8023984}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1599, "y": 472}, "vk": "default", "time": 1594977557.8143992}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1600, "y": 472}, "vk": "default", "time": 1594977557.8223994}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1602, "y": 472}, "vk": "default", "time": 1594977557.8344002}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1604, "y": 473}, "vk": "default", "time": 1594977557.8424008}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1606, "y": 473}, "vk": "default", "time": 1594977557.8504012}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1608, "y": 473}, "vk": "default", "time": 1594977557.8624017}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1611, "y": 473}, "vk": "default", "time": 1594977557.8704023}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1613, "y": 473}, "vk": "default", "time": 1594977557.8784027}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1615, "y": 474}, "vk": "default", "time": 1594977557.8904035}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1616, "y": 474}, "vk": "default", "time": 1594977557.8984041}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1617, "y": 474}, "vk": "default", "time": 1594977557.9104047}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1618, "y": 474}, "vk": "default", "time": 1594977557.918405}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1620, "y": 475}, "vk": "default", "time": 1594977557.9264057}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1620, "y": 475}, "vk": "default", "time": 1594977557.9384065}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1621, "y": 476}, "vk": "default", "time": 1594977557.950407}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1622, "y": 476}, "vk": "default", "time": 1594977557.9584074}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1623, "y": 476}, "vk": "default", "time": 1594977557.966408}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1623, "y": 476}, "vk": "default", "time": 1594977557.9784088}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1624, "y": 476}, "vk": "default", "time": 1594977557.986409}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1625, "y": 477}, "vk": "default", "time": 1594977557.9944096}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1626, "y": 477}, "vk": "default", "time": 1594977558.0064101}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1626, "y": 477}, "vk": "default", "time": 1594977558.0144105}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1626, "y": 478}, "vk": "default", "time": 1594977558.0264113}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1627, "y": 478}, "vk": "default", "time": 1594977558.0344117}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1627, "y": 479}, "vk": "default", "time": 1594977558.0464122}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1628, "y": 479}, "vk": "default", "time": 1594977558.1504185}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1628, "y": 479}, "vk": "default", "time": 1594977558.3424294}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1628, "y": 480}, "vk": "default", "time": 1594977558.3744311}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1628, "y": 480}, "vk": "default", "time": 1594977558.390432}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1628, "y": 481}, "vk": "default", "time": 1594977558.4024327}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 1628, "y": 481}, "vk": "default", "time": 1594977558.8664594}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 1628, "y": 481}, "vk": "default", "time": 1594977559.0744715}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1629, "y": 481}, "vk": "default", "time": 1594977559.4264915}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1630, "y": 479}, "vk": "default", "time": 1594977559.438492}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1632, "y": 478}, "vk": "default", "time": 1594977559.4464924}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1636, "y": 475}, "vk": "default", "time": 1594977559.4584932}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1641, "y": 472}, "vk": "default", "time": 1594977559.4664936}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1647, "y": 469}, "vk": "default", "time": 1594977559.4744942}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1651, "y": 466}, "vk": "default", "time": 1594977559.4864948}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1656, "y": 464}, "vk": "default", "time": 1594977559.4944952}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1660, "y": 461}, "vk": "default", "time": 1594977559.506496}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1663, "y": 458}, "vk": "default", "time": 1594977559.5144966}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1667, "y": 456}, "vk": "default", "time": 1594977559.522497}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1671, "y": 452}, "vk": "default", "time": 1594977559.5344975}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1675, "y": 446}, "vk": "default", "time": 1594977559.542498}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1678, "y": 442}, "vk": "default", "time": 1594977559.554499}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1681, "y": 438}, "vk": "default", "time": 1594977559.562499}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1684, "y": 435}, "vk": "default", "time": 1594977559.5744998}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1687, "y": 430}, "vk": "default", "time": 1594977559.5825005}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1688, "y": 428}, "vk": "default", "time": 1594977559.594501}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1691, "y": 424}, "vk": "default", "time": 1594977559.6025014}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1692, "y": 422}, "vk": "default", "time": 1594977559.610502}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1694, "y": 420}, "vk": "default", "time": 1594977559.6225026}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1695, "y": 417}, "vk": "default", "time": 1594977559.6305032}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1696, "y": 414}, "vk": "default", "time": 1594977559.6415038}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1698, "y": 412}, "vk": "default", "time": 1594977559.650504}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1698, "y": 411}, "vk": "default", "time": 1594977559.6585047}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 408}, "vk": "default", "time": 1594977559.6705053}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 407}, "vk": "default", "time": 1594977559.6785057}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 406}, "vk": "default", "time": 1594977559.6905065}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 405}, "vk": "default", "time": 1594977559.698507}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 404}, "vk": "default", "time": 1594977559.7065074}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 403}, "vk": "default", "time": 1594977559.718508}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 403}, "vk": "default", "time": 1594977559.7265086}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 402}, "vk": "default", "time": 1594977559.737509}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 402}, "vk": "default", "time": 1594977559.7465098}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 401}, "vk": "default", "time": 1594977559.7585104}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 400}, "vk": "default", "time": 1594977559.7735112}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 400}, "vk": "default", "time": 1594977559.786512}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 399}, "vk": "default", "time": 1594977559.806513}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 399}, "vk": "default", "time": 1594977559.854516}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 398}, "vk": "default", "time": 1594977559.8625162}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 397}, "vk": "default", "time": 1594977559.8825176}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 397}, "vk": "default", "time": 1594977559.890518}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1699, "y": 396}, "vk": "default", "time": 1594977559.9025185}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1698, "y": 396}, "vk": "default", "time": 1594977559.9105191}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1698, "y": 395}, "vk": "default", "time": 1594977559.92252}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1697, "y": 395}, "vk": "default", "time": 1594977559.9385207}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1697, "y": 394}, "vk": "default", "time": 1594977559.9505212}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1697, "y": 394}, "vk": "default", "time": 1594977559.9705226}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1696, "y": 393}, "vk": "default", "time": 1594977559.9785228}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1695, "y": 393}, "vk": "default", "time": 1594977559.9865234}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1695, "y": 393}, "vk": "default", "time": 1594977559.9985242}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1694, "y": 392}, "vk": "default", "time": 1594977560.0055244}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1693, "y": 392}, "vk": "default", "time": 1594977560.0185251}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1692, "y": 392}, "vk": "default", "time": 1594977560.0265257}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1692, "y": 391}, "vk": "default", "time": 1594977560.034526}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1691, "y": 391}, "vk": "default", "time": 1594977560.0465267}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1690, "y": 390}, "vk": "default", "time": 1594977560.0545273}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1689, "y": 390}, "vk": "default", "time": 1594977560.066528}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1689, "y": 389}, "vk": "default", "time": 1594977560.0745285}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1688, "y": 388}, "vk": "default", "time": 1594977560.086529}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1688, "y": 387}, "vk": "default", "time": 1594977560.0945296}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1687, "y": 387}, "vk": "default", "time": 1594977560.1065302}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1687, "y": 386}, "vk": "default", "time": 1594977560.1145308}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1686, "y": 386}, "vk": "default", "time": 1594977560.1225314}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1686, "y": 385}, "vk": "default", "time": 1594977560.1345317}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1686, "y": 384}, "vk": "default", "time": 1594977560.1465325}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1686, "y": 384}, "vk": "default", "time": 1594977560.1545331}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1686, "y": 383}, "vk": "default", "time": 1594977560.1625333}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1686, "y": 382}, "vk": "default", "time": 1594977560.174534}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1686, "y": 381}, "vk": "default", "time": 1594977560.1825347}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1686, "y": 381}, "vk": "default", "time": 1594977560.190535}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1685, "y": 380}, "vk": "default", "time": 1594977560.2025356}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1685, "y": 379}, "vk": "default", "time": 1594977560.2105362}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1684, "y": 379}, "vk": "default", "time": 1594977560.222537}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1684, "y": 378}, "vk": "default", "time": 1594977560.2305374}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 378}, "vk": "default", "time": 1594977560.2505386}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 378}, "vk": "default", "time": 1594977561.8776314}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 379}, "vk": "default", "time": 1594977561.885632}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 380}, "vk": "default", "time": 1594977561.8976328}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 381}, "vk": "default", "time": 1594977561.9056332}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 382}, "vk": "default", "time": 1594977561.9136336}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 382}, "vk": "default", "time": 1594977561.9336348}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 383}, "vk": "default", "time": 1594977561.9456356}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 384}, "vk": "default", "time": 1594977561.953636}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 385}, "vk": "default", "time": 1594977561.9616363}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 386}, "vk": "default", "time": 1594977561.973637}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 387}, "vk": "default", "time": 1594977561.9816375}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 387}, "vk": "default", "time": 1594977562.0016387}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 388}, "vk": "default", "time": 1594977562.0096393}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1683, "y": 388}, "vk": "default", "time": 1594977562.0296402}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 1683, "y": 388}, "vk": "default", "time": 1594977563.3667169}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1684, "y": 388}, "vk": "default", "time": 1594977563.841744}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1686, "y": 388}, "vk": "default", "time": 1594977563.8497443}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1688, "y": 389}, "vk": "default", "time": 1594977563.861745}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1691, "y": 389}, "vk": "default", "time": 1594977563.8697455}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1694, "y": 390}, "vk": "default", "time": 1594977563.8817463}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1697, "y": 391}, "vk": "default", "time": 1594977563.8897467}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1700, "y": 391}, "vk": "default", "time": 1594977563.9017475}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1703, "y": 392}, "vk": "default", "time": 1594977563.9097476}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1706, "y": 392}, "vk": "default", "time": 1594977563.9177482}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1710, "y": 394}, "vk": "default", "time": 1594977563.929749}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1715, "y": 397}, "vk": "default", "time": 1594977563.9377494}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1720, "y": 399}, "vk": "default", "time": 1594977563.94575}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1725, "y": 402}, "vk": "default", "time": 1594977563.9577506}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1728, "y": 403}, "vk": "default", "time": 1594977563.965751}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1730, "y": 403}, "vk": "default", "time": 1594977563.9777517}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1733, "y": 406}, "vk": "default", "time": 1594977563.9857523}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1736, "y": 408}, "vk": "default", "time": 1594977563.9937525}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1738, "y": 410}, "vk": "default", "time": 1594977564.0057533}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1740, "y": 411}, "vk": "default", "time": 1594977564.013754}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1744, "y": 412}, "vk": "default", "time": 1594977564.0257545}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1746, "y": 414}, "vk": "default", "time": 1594977564.0337548}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1747, "y": 415}, "vk": "default", "time": 1594977564.0417554}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1751, "y": 417}, "vk": "default", "time": 1594977564.053756}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1752, "y": 418}, "vk": "default", "time": 1594977564.0617564}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1755, "y": 421}, "vk": "default", "time": 1594977564.0737572}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1758, "y": 422}, "vk": "default", "time": 1594977564.0817578}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1761, "y": 424}, "vk": "default", "time": 1594977564.0897582}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1763, "y": 425}, "vk": "default", "time": 1594977564.1017587}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1766, "y": 426}, "vk": "default", "time": 1594977564.1097593}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1768, "y": 428}, "vk": "default", "time": 1594977564.1177597}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1771, "y": 429}, "vk": "default", "time": 1594977564.1297605}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1773, "y": 430}, "vk": "default", "time": 1594977564.141761}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1776, "y": 432}, "vk": "default", "time": 1594977564.1497614}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1778, "y": 432}, "vk": "default", "time": 1594977564.158762}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1780, "y": 434}, "vk": "default", "time": 1594977564.1657627}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1782, "y": 435}, "vk": "default", "time": 1594977564.177763}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1785, "y": 436}, "vk": "default", "time": 1594977564.1857636}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1787, "y": 437}, "vk": "default", "time": 1594977564.1977644}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1790, "y": 438}, "vk": "default", "time": 1594977564.2057645}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1792, "y": 439}, "vk": "default", "time": 1594977564.2177653}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1795, "y": 440}, "vk": "default", "time": 1594977564.225766}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1798, "y": 441}, "vk": "default", "time": 1594977564.2337663}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1801, "y": 441}, "vk": "default", "time": 1594977564.2457669}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1804, "y": 443}, "vk": "default", "time": 1594977564.2537675}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1810, "y": 444}, "vk": "default", "time": 1594977564.2657683}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1813, "y": 445}, "vk": "default", "time": 1594977564.2737687}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1816, "y": 446}, "vk": "default", "time": 1594977564.2857692}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1820, "y": 449}, "vk": "default", "time": 1594977564.2937698}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1823, "y": 451}, "vk": "default", "time": 1594977564.3057704}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1826, "y": 452}, "vk": "default", "time": 1594977564.313771}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1829, "y": 454}, "vk": "default", "time": 1594977564.3217716}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1831, "y": 455}, "vk": "default", "time": 1594977564.333772}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1834, "y": 456}, "vk": "default", "time": 1594977564.3457727}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1837, "y": 457}, "vk": "default", "time": 1594977564.3537734}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1840, "y": 458}, "vk": "default", "time": 1594977564.3617737}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1842, "y": 459}, "vk": "default", "time": 1594977564.369774}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1844, "y": 459}, "vk": "default", "time": 1594977564.381775}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1846, "y": 459}, "vk": "default", "time": 1594977564.3897753}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1849, "y": 460}, "vk": "default", "time": 1594977564.401776}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1850, "y": 461}, "vk": "default", "time": 1594977564.4097764}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1852, "y": 461}, "vk": "default", "time": 1594977564.4177768}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1854, "y": 461}, "vk": "default", "time": 1594977564.4297776}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1854, "y": 461}, "vk": "default", "time": 1594977564.437778}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1855, "y": 461}, "vk": "default", "time": 1594977564.4497788}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1855, "y": 461}, "vk": "default", "time": 1594977564.4577792}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1856, "y": 461}, "vk": "default", "time": 1594977564.4657798}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1857, "y": 461}, "vk": "default", "time": 1594977564.4777803}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1857, "y": 461}, "vk": "default", "time": 1594977564.489781}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1858, "y": 461}, "vk": "default", "time": 1594977564.4977815}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1858, "y": 461}, "vk": "default", "time": 1594977564.5057821}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1859, "y": 461}, "vk": "default", "time": 1594977564.5177824}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1859, "y": 461}, "vk": "default", "time": 1594977564.5377839}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1860, "y": 462}, "vk": "default", "time": 1594977564.5457842}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1861, "y": 462}, "vk": "default", "time": 1594977564.5577848}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1862, "y": 462}, "vk": "default", "time": 1594977564.5737858}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1862, "y": 462}, "vk": "default", "time": 1594977564.593787}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1863, "y": 462}, "vk": "default", "time": 1594977564.6337893}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1864, "y": 463}, "vk": "default", "time": 1594977564.6417897}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1865, "y": 463}, "vk": "default", "time": 1594977564.6497903}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1865, "y": 464}, "vk": "default", "time": 1594977564.6617906}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1866, "y": 464}, "vk": "default", "time": 1594977564.6697912}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1867, "y": 465}, "vk": "default", "time": 1594977564.681792}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1868, "y": 466}, "vk": "default", "time": 1594977564.6897924}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1869, "y": 467}, "vk": "default", "time": 1594977564.697793}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1869, "y": 468}, "vk": "default", "time": 1594977564.7097936}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1870, "y": 469}, "vk": "default", "time": 1594977564.717794}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1871, "y": 469}, "vk": "default", "time": 1594977564.7297947}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1872, "y": 470}, "vk": "default", "time": 1594977564.737795}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1872, "y": 471}, "vk": "default", "time": 1594977564.7457955}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1872, "y": 472}, "vk": "default", "time": 1594977564.7577963}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 472}, "vk": "default", "time": 1594977564.7777975}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 473}, "vk": "default", "time": 1594977564.7857978}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 474}, "vk": "default", "time": 1594977564.8338008}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 474}, "vk": "default", "time": 1594977564.8618023}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 475}, "vk": "default", "time": 1594977564.873803}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 475}, "vk": "default", "time": 1594977564.893804}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 476}, "vk": "default", "time": 1594977564.9018044}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 477}, "vk": "default", "time": 1594977564.909805}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 478}, "vk": "default", "time": 1594977564.9218059}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 478}, "vk": "default", "time": 1594977564.929806}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 479}, "vk": "default", "time": 1594977564.9418068}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 480}, "vk": "default", "time": 1594977564.9498074}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 480}, "vk": "default", "time": 1594977564.961808}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 481}, "vk": "default", "time": 1594977564.9698083}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 481}, "vk": "default", "time": 1594977564.9898098}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 482}, "vk": "default", "time": 1594977564.99781}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 482}, "vk": "default", "time": 1594977565.0938156}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 483}, "vk": "default", "time": 1594977565.1818206}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 484}, "vk": "default", "time": 1594977565.2378237}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 484}, "vk": "default", "time": 1594977565.3258288}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 485}, "vk": "default", "time": 1594977565.4818377}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 485}, "vk": "default", "time": 1594977565.5978444}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1873, "y": 486}, "vk": "default", "time": 1594977565.6178455}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 1873, "y": 486}, "vk": "default", "time": 1594977565.8298576}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594977566.803913}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 67, "time": 1594977567.2679398}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 67, "time": 1594977567.3879468}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 67, "time": 1594977567.5079536}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 67, "time": 1594977567.5879583}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1594977567.6839635}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 27, "time": 1594977568.964037}
