{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 698, "y": 512}, "vk": "default", "time": 1595234769.242746}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 512}, "vk": "default", "time": 1595234769.258748}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 513}, "vk": "default", "time": 1595234769.2747502}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 514}, "vk": "default", "time": 1595234769.2827513}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 514}, "vk": "default", "time": 1595234769.2907522}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 515}, "vk": "default", "time": 1595234769.2987533}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 515}, "vk": "default", "time": 1595234769.3067544}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 516}, "vk": "default", "time": 1595234769.314755}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 516}, "vk": "default", "time": 1595234769.3307574}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 517}, "vk": "default", "time": 1595234769.3467593}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 518}, "vk": "default", "time": 1595234769.3547602}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 518}, "vk": "default", "time": 1595234769.3627613}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 519}, "vk": "default", "time": 1595234769.3707626}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 519}, "vk": "default", "time": 1595234769.3787634}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 698, "y": 520}, "vk": "default", "time": 1595234769.3867643}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 698, "y": 521}, "vk": "default", "time": 1595234769.3947654}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 698, "y": 521}, "vk": "default", "time": 1595234769.4027662}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 698, "y": 522}, "vk": "default", "time": 1595234769.4107673}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 698, "y": 522}, "vk": "default", "time": 1595234769.4347703}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 697, "y": 522}, "vk": "default", "time": 1595234769.4587736}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 697, "y": 523}, "vk": "default", "time": 1595234769.4667745}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 697, "y": 523}, "vk": "default", "time": 1595234769.5227816}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 697, "y": 523}, "vk": "default", "time": 1595234769.5307827}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 696, "y": 523}, "vk": "default", "time": 1595234769.5387838}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 696, "y": 524}, "vk": "default", "time": 1595234769.5467849}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 696, "y": 525}, "vk": "default", "time": 1595234769.5547857}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 696, "y": 525}, "vk": "default", "time": 1595234769.5867898}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 695, "y": 525}, "vk": "default", "time": 1595234769.6107926}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 695, "y": 526}, "vk": "default", "time": 1595234769.626795}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 694, "y": 526}, "vk": "default", "time": 1595234769.6427968}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 694, "y": 526}, "vk": "default", "time": 1595234770.194867}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 694, "y": 526}, "vk": "default", "time": 1595234770.3148823}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 694, "y": 529}, "vk": "default", "time": 1595234771.8030713}
