{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 877, "y": 135}, "vk": "default", "time": 1595386037.4238281}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 877, "y": 134}, "vk": "default", "time": 1595386037.856445}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 877, "y": 133}, "vk": "default", "time": 1595386037.9785156}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 876, "y": 129}, "vk": "default", "time": 1595386038.0664062}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 874, "y": 128}, "vk": "default", "time": 1595386038.1552734}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 873, "y": 128}, "vk": "default", "time": 1595386038.3330078}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 873, "y": 128}, "vk": "default", "time": 1595386039.5654294}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 873, "y": 128}, "vk": "default", "time": 1595386039.5654294}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 873, "y": 128}, "vk": "default", "time": 1595386039.7929688}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 873, "y": 128}, "vk": "default", "time": 1595386039.7939453}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 27, "time": 1595386041.1826172}
