{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 503, "y": 299}, "vk": "default", "time": 1599534318.3161263}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 504, "y": 298}, "vk": "default", "time": 1599534318.328127}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 505, "y": 298}, "vk": "default", "time": 1599534318.3361275}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 505, "y": 298}, "vk": "default", "time": 1599534318.344128}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 505, "y": 297}, "vk": "default", "time": 1599534318.3521285}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 506, "y": 297}, "vk": "default", "time": 1599534318.3641293}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 506, "y": 297}, "vk": "default", "time": 1599534318.4121318}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 507, "y": 297}, "vk": "default", "time": 1599534318.4321332}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 508, "y": 296}, "vk": "default", "time": 1599534318.4441335}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 508, "y": 295}, "vk": "default", "time": 1599534318.448134}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 508, "y": 294}, "vk": "default", "time": 1599534318.4601347}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 509, "y": 294}, "vk": "default", "time": 1599534318.4721353}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 509, "y": 293}, "vk": "default", "time": 1599534318.4921365}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 509, "y": 293}, "vk": "default", "time": 1599534318.4961367}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 509, "y": 292}, "vk": "default", "time": 1599534318.5081375}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 509, "y": 291}, "vk": "default", "time": 1599534318.5281384}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 509, "y": 291}, "vk": "default", "time": 1599534318.5401392}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 509, "y": 291}, "vk": "default", "time": 1599534318.604143}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 510, "y": 290}, "vk": "default", "time": 1599534318.6241438}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 510, "y": 290}, "vk": "default", "time": 1599534318.6361446}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 511, "y": 290}, "vk": "default", "time": 1599534318.6401448}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 512, "y": 289}, "vk": "default", "time": 1599534318.6521456}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 514, "y": 289}, "vk": "default", "time": 1599534318.6641462}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 515, "y": 289}, "vk": "default", "time": 1599534318.6721468}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 515, "y": 289}, "vk": "default", "time": 1599534318.6841474}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 517, "y": 289}, "vk": "default", "time": 1599534318.6881478}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 518, "y": 289}, "vk": "default", "time": 1599534318.7001486}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 519, "y": 289}, "vk": "default", "time": 1599534318.712149}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 519, "y": 289}, "vk": "default", "time": 1599534318.7201495}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 520, "y": 289}, "vk": "default", "time": 1599534318.7321503}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 520, "y": 289}, "vk": "default", "time": 1599534318.748151}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 521, "y": 289}, "vk": "default", "time": 1599534318.7601519}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 521, "y": 289}, "vk": "default", "time": 1599534318.7961538}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 522, "y": 289}, "vk": "default", "time": 1599534318.816155}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 522, "y": 289}, "vk": "default", "time": 1599534318.9441624}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 522, "y": 290}, "vk": "default", "time": 1599534318.9561632}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 522, "y": 290}, "vk": "default", "time": 1599534319.7322073}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 522, "y": 290}, "vk": "default", "time": 1599534319.9402194}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 522, "y": 290}, "vk": "default", "time": 1599534321.1642892}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 522, "y": 290}, "vk": "default", "time": 1599534321.4083033}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 522, "y": 290}, "vk": "default", "time": 1599534321.4203038}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 522, "y": 290}, "vk": "default", "time": 1599534321.4283044}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 522, "y": 290}, "vk": "default", "time": 1599534331.6118867}
