{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 359, "y": 516}, "vk": "default", "time": 1604311258.9856832}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 358, "y": 517}, "vk": "default", "time": 1604311258.9896834}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 358, "y": 517}, "vk": "default", "time": 1604311259.0016842}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 357, "y": 518}, "vk": "default", "time": 1604311259.0136847}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 357, "y": 518}, "vk": "default", "time": 1604311259.0216854}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 355, "y": 518}, "vk": "default", "time": 1604311259.033686}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 355, "y": 519}, "vk": "default", "time": 1604311259.037686}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 519}, "vk": "default", "time": 1604311259.0496867}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 519}, "vk": "default", "time": 1604311259.0616875}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 519}, "vk": "default", "time": 1604311259.0816886}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 519}, "vk": "default", "time": 1604311259.0856888}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 352, "y": 519}, "vk": "default", "time": 1604311259.10569}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 351, "y": 519}, "vk": "default", "time": 1604311259.1296914}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 351, "y": 519}, "vk": "default", "time": 1604311259.1336915}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 350, "y": 519}, "vk": "default", "time": 1604311259.1656935}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 350, "y": 519}, "vk": "default", "time": 1604311259.1776943}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 349, "y": 519}, "vk": "default", "time": 1604311259.193695}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 348, "y": 519}, "vk": "default", "time": 1604311259.2136962}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 348, "y": 519}, "vk": "default", "time": 1604311259.225697}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 347, "y": 519}, "vk": "default", "time": 1604311259.261699}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 347, "y": 519}, "vk": "default", "time": 1604311259.2736995}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 346, "y": 519}, "vk": "default", "time": 1604311259.2897005}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 346, "y": 519}, "vk": "default", "time": 1604311259.3097017}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 345, "y": 519}, "vk": "default", "time": 1604311259.3217025}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 344, "y": 519}, "vk": "default", "time": 1604311259.3417034}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 344, "y": 519}, "vk": "default", "time": 1604311259.3537042}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 344, "y": 519}, "vk": "default", "time": 1604311259.925737}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 344, "y": 519}, "vk": "default", "time": 1604311260.1297486}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604311265.888078}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 86, "time": 1604311266.3841062}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 86, "time": 1604311266.5121136}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604311266.5441155}