{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 698, "y": 535}, "vk": "default", "time": 1604311331.1298096}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 698, "y": 537}, "vk": "default", "time": 1604311331.1338098}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 698, "y": 538}, "vk": "default", "time": 1604311331.1458104}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 539}, "vk": "default", "time": 1604311331.153811}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 700, "y": 540}, "vk": "default", "time": 1604311331.1658118}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 700, "y": 541}, "vk": "default", "time": 1604311331.1778123}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 700, "y": 542}, "vk": "default", "time": 1604311331.1818125}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 700, "y": 543}, "vk": "default", "time": 1604311331.1938133}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 700, "y": 543}, "vk": "default", "time": 1604311331.2018137}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 700, "y": 544}, "vk": "default", "time": 1604311331.2138143}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 701, "y": 545}, "vk": "default", "time": 1604311331.225815}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 701, "y": 546}, "vk": "default", "time": 1604311331.2298152}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 701, "y": 546}, "vk": "default", "time": 1604311331.241816}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 701, "y": 547}, "vk": "default", "time": 1604311331.261817}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 701, "y": 547}, "vk": "default", "time": 1604311331.325821}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 701, "y": 548}, "vk": "default", "time": 1604311331.3378215}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 701, "y": 548}, "vk": "default", "time": 1604311331.3498223}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 702, "y": 549}, "vk": "default", "time": 1604311331.3578227}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 703, "y": 549}, "vk": "default", "time": 1604311331.3698232}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 704, "y": 549}, "vk": "default", "time": 1604311331.381824}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 704, "y": 550}, "vk": "default", "time": 1604311331.3858242}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 704, "y": 550}, "vk": "default", "time": 1604311331.401825}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 706, "y": 550}, "vk": "default", "time": 1604311331.4058254}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 706, "y": 551}, "vk": "default", "time": 1604311331.417826}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 707, "y": 551}, "vk": "default", "time": 1604311331.4298267}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 707, "y": 552}, "vk": "default", "time": 1604311331.4338272}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 707, "y": 552}, "vk": "default", "time": 1604311331.4458275}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 708, "y": 552}, "vk": "default", "time": 1604311331.453828}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 709, "y": 552}, "vk": "default", "time": 1604311331.465829}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 709, "y": 552}, "vk": "default", "time": 1604311331.4818296}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 710, "y": 553}, "vk": "default", "time": 1604311331.4938304}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 710, "y": 553}, "vk": "default", "time": 1604311331.5138314}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 710, "y": 553}, "vk": "default", "time": 1604311331.5258322}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 711, "y": 554}, "vk": "default", "time": 1604311331.5338328}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 712, "y": 554}, "vk": "default", "time": 1604311331.5458336}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 712, "y": 554}, "vk": "default", "time": 1604311331.5618343}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 554}, "vk": "default", "time": 1604311331.573835}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 555}, "vk": "default", "time": 1604311331.7058425}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 557}, "vk": "default", "time": 1604311331.7178433}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 557}, "vk": "default", "time": 1604311331.7258437}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 558}, "vk": "default", "time": 1604311331.7378442}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 559}, "vk": "default", "time": 1604311331.765846}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 560}, "vk": "default", "time": 1604311331.785847}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 561}, "vk": "default", "time": 1604311331.7978477}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 561}, "vk": "default", "time": 1604311331.83385}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 562}, "vk": "default", "time": 1604311331.8818526}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 562}, "vk": "default", "time": 1604311331.8978534}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 563}, "vk": "default", "time": 1604311331.9098542}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 564}, "vk": "default", "time": 1604311331.9298553}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 564}, "vk": "default", "time": 1604311331.941856}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 565}, "vk": "default", "time": 1604311331.9578571}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 565}, "vk": "default", "time": 1604311331.977858}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 566}, "vk": "default", "time": 1604311331.9898589}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 566}, "vk": "default", "time": 1604311331.993859}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 567}, "vk": "default", "time": 1604311332.0218606}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 567}, "vk": "default", "time": 1604311332.0378613}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 568}, "vk": "default", "time": 1604311332.0698633}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 568}, "vk": "default", "time": 1604311332.0858643}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 568}, "vk": "default", "time": 1604311332.0938647}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 569}, "vk": "default", "time": 1604311332.1058655}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 569}, "vk": "default", "time": 1604311332.1218662}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 569}, "vk": "default", "time": 1604311332.133867}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 570}, "vk": "default", "time": 1604311332.1658688}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 713, "y": 571}, "vk": "default", "time": 1604311332.2618742}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 712, "y": 571}, "vk": "default", "time": 1604311332.4178832}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 712, "y": 571}, "vk": "default", "time": 1604311334.3259923}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 712, "y": 571}, "vk": "default", "time": 1604311334.5340042}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 712, "y": 571}, "vk": "default", "time": 1604311335.405054}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 712, "y": 571}, "vk": "default", "time": 1604311335.613066}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 712, "y": 571}, "vk": "default", "time": 1604311338.5812356}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 712, "y": 571}, "vk": "default", "time": 1604311338.7892478}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 711, "y": 570}, "vk": "default", "time": 1604311343.1054945}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 709, "y": 570}, "vk": "default", "time": 1604311343.1174953}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 709, "y": 569}, "vk": "default", "time": 1604311343.125496}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 706, "y": 568}, "vk": "default", "time": 1604311343.1374962}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 704, "y": 566}, "vk": "default", "time": 1604311343.1414967}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 703, "y": 565}, "vk": "default", "time": 1604311343.1574976}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 702, "y": 565}, "vk": "default", "time": 1604311343.1694982}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 701, "y": 563}, "vk": "default", "time": 1604311343.1734984}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 700, "y": 563}, "vk": "default", "time": 1604311343.1854992}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 563}, "vk": "default", "time": 1604311343.1894994}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 699, "y": 562}, "vk": "default", "time": 1604311343.2015}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 697, "y": 562}, "vk": "default", "time": 1604311343.2135007}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 696, "y": 561}, "vk": "default", "time": 1604311343.221501}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 694, "y": 560}, "vk": "default", "time": 1604311343.233502}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 692, "y": 558}, "vk": "default", "time": 1604311343.2455025}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 690, "y": 558}, "vk": "default", "time": 1604311343.253503}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 688, "y": 556}, "vk": "default", "time": 1604311343.2655036}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 686, "y": 555}, "vk": "default", "time": 1604311343.269504}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 684, "y": 553}, "vk": "default", "time": 1604311343.2815046}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 682, "y": 552}, "vk": "default", "time": 1604311343.2935052}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 680, "y": 551}, "vk": "default", "time": 1604311343.3015058}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 679, "y": 551}, "vk": "default", "time": 1604311343.3135064}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 677, "y": 550}, "vk": "default", "time": 1604311343.3175068}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 676, "y": 550}, "vk": "default", "time": 1604311343.3295074}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 674, "y": 549}, "vk": "default", "time": 1604311343.3415082}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 672, "y": 549}, "vk": "default", "time": 1604311343.3495085}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 670, "y": 547}, "vk": "default", "time": 1604311343.361509}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 667, "y": 546}, "vk": "default", "time": 1604311343.37351}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 664, "y": 546}, "vk": "default", "time": 1604311343.37751}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 661, "y": 545}, "vk": "default", "time": 1604311343.3895109}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 657, "y": 543}, "vk": "default", "time": 1604311343.3975112}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 653, "y": 543}, "vk": "default", "time": 1604311343.409512}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 650, "y": 542}, "vk": "default", "time": 1604311343.4135122}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 644, "y": 541}, "vk": "default", "time": 1604311343.4255128}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 640, "y": 541}, "vk": "default", "time": 1604311343.4375136}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 634, "y": 539}, "vk": "default", "time": 1604311343.445514}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 631, "y": 538}, "vk": "default", "time": 1604311343.4575148}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 626, "y": 538}, "vk": "default", "time": 1604311343.461515}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 623, "y": 536}, "vk": "default", "time": 1604311343.4735155}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 620, "y": 535}, "vk": "default", "time": 1604311343.4855163}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 617, "y": 534}, "vk": "default", "time": 1604311343.4935167}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 614, "y": 533}, "vk": "default", "time": 1604311343.5055172}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 611, "y": 532}, "vk": "default", "time": 1604311343.517518}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 609, "y": 531}, "vk": "default", "time": 1604311343.5215182}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 607, "y": 530}, "vk": "default", "time": 1604311343.533519}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 604, "y": 529}, "vk": "default", "time": 1604311343.5415196}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 601, "y": 528}, "vk": "default", "time": 1604311343.5535202}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 599, "y": 527}, "vk": "default", "time": 1604311343.5575204}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 596, "y": 526}, "vk": "default", "time": 1604311343.5695212}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 593, "y": 525}, "vk": "default", "time": 1604311343.581522}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 589, "y": 524}, "vk": "default", "time": 1604311343.5895221}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 587, "y": 523}, "vk": "default", "time": 1604311343.601523}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 584, "y": 522}, "vk": "default", "time": 1604311343.6135237}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 582, "y": 521}, "vk": "default", "time": 1604311343.6175237}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 579, "y": 521}, "vk": "default", "time": 1604311343.6295245}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 577, "y": 520}, "vk": "default", "time": 1604311343.637525}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 575, "y": 519}, "vk": "default", "time": 1604311343.6495256}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 573, "y": 519}, "vk": "default", "time": 1604311343.6615262}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 571, "y": 518}, "vk": "default", "time": 1604311343.6695268}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 569, "y": 517}, "vk": "default", "time": 1604311343.6815276}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 567, "y": 516}, "vk": "default", "time": 1604311343.6855278}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 566, "y": 516}, "vk": "default", "time": 1604311343.6975284}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 565, "y": 516}, "vk": "default", "time": 1604311343.7095292}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 564, "y": 515}, "vk": "default", "time": 1604311343.7135293}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 561, "y": 515}, "vk": "default", "time": 1604311343.7255301}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 559, "y": 515}, "vk": "default", "time": 1604311343.7335305}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 556, "y": 515}, "vk": "default", "time": 1604311343.745531}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 554, "y": 515}, "vk": "default", "time": 1604311343.757532}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 551, "y": 515}, "vk": "default", "time": 1604311343.7655325}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 549, "y": 515}, "vk": "default", "time": 1604311343.7775328}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 547, "y": 515}, "vk": "default", "time": 1604311343.7815332}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 546, "y": 515}, "vk": "default", "time": 1604311343.793534}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 545, "y": 515}, "vk": "default", "time": 1604311343.8055346}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 543, "y": 515}, "vk": "default", "time": 1604311343.813535}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 540, "y": 515}, "vk": "default", "time": 1604311343.8255358}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 538, "y": 515}, "vk": "default", "time": 1604311343.829536}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 536, "y": 515}, "vk": "default", "time": 1604311343.8415365}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 533, "y": 515}, "vk": "default", "time": 1604311343.8535373}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 531, "y": 515}, "vk": "default", "time": 1604311343.8615377}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 529, "y": 515}, "vk": "default", "time": 1604311343.8735385}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 529, "y": 515}, "vk": "default", "time": 1604311343.877539}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 528, "y": 515}, "vk": "default", "time": 1604311343.8895392}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 526, "y": 515}, "vk": "default", "time": 1604311343.90154}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 526, "y": 515}, "vk": "default", "time": 1604311343.9095407}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 524, "y": 515}, "vk": "default", "time": 1604311343.9215412}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 522, "y": 516}, "vk": "default", "time": 1604311343.9255414}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 519, "y": 516}, "vk": "default", "time": 1604311343.9375422}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 517, "y": 517}, "vk": "default", "time": 1604311343.949543}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 516, "y": 517}, "vk": "default", "time": 1604311343.9575434}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 515, "y": 517}, "vk": "default", "time": 1604311343.969544}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 514, "y": 518}, "vk": "default", "time": 1604311343.9735441}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 512, "y": 518}, "vk": "default", "time": 1604311343.985545}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 512, "y": 519}, "vk": "default", "time": 1604311343.9975455}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 511, "y": 519}, "vk": "default", "time": 1604311344.005546}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 511, "y": 520}, "vk": "default", "time": 1604311344.0175467}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 510, "y": 520}, "vk": "default", "time": 1604311344.0295475}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 510, "y": 520}, "vk": "default", "time": 1604311344.0335474}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 509, "y": 520}, "vk": "default", "time": 1604311344.0935512}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 508, "y": 521}, "vk": "default", "time": 1604311344.113552}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 508, "y": 521}, "vk": "default", "time": 1604311344.125553}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 507, "y": 522}, "vk": "default", "time": 1604311344.129553}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 507, "y": 523}, "vk": "default", "time": 1604311344.1415539}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 506, "y": 523}, "vk": "default", "time": 1604311344.1495543}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 506, "y": 524}, "vk": "default", "time": 1604311344.161555}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 505, "y": 524}, "vk": "default", "time": 1604311344.1735556}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 505, "y": 524}, "vk": "default", "time": 1604311345.069607}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 505, "y": 524}, "vk": "default", "time": 1604311345.2776186}