{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 748, "y": 432}, "vk": "default", "time": 1604371886.1426997}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 748, "y": 433}, "vk": "default", "time": 1604371886.1587007}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 748, "y": 434}, "vk": "default", "time": 1604371886.1707013}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 749, "y": 434}, "vk": "default", "time": 1604371886.1747015}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 749, "y": 435}, "vk": "default", "time": 1604371886.1867023}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 749, "y": 435}, "vk": "default", "time": 1604371886.1907027}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 749, "y": 436}, "vk": "default", "time": 1604371886.202703}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 749, "y": 436}, "vk": "default", "time": 1604371886.302709}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 749, "y": 437}, "vk": "default", "time": 1604371886.49472}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 749, "y": 437}, "vk": "default", "time": 1604371886.510721}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 749, "y": 438}, "vk": "default", "time": 1604371886.5227215}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 750, "y": 439}, "vk": "default", "time": 1604371886.5427227}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 751, "y": 439}, "vk": "default", "time": 1604371886.566724}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 751, "y": 440}, "vk": "default", "time": 1604371886.5707242}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 751, "y": 440}, "vk": "default", "time": 1604371886.5907254}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 751, "y": 440}, "vk": "default", "time": 1604371887.1307564}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 751, "y": 440}, "vk": "default", "time": 1604371887.3387682}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604371888.1648157}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 86, "time": 1604371888.508835}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 86, "time": 1604371888.6368425}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604371888.6848452}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 27, "time": 1604371889.803909}
