{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 741, "y": 352}, "vk": "default", "time": 1604376114.9605744}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 741, "y": 352}, "vk": "default", "time": 1604376114.9685748}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 741, "y": 353}, "vk": "default", "time": 1604376114.9805756}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 742, "y": 355}, "vk": "default", "time": 1604376114.9845757}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 743, "y": 355}, "vk": "default", "time": 1604376114.9965765}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 743, "y": 357}, "vk": "default", "time": 1604376115.008577}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 743, "y": 358}, "vk": "default", "time": 1604376115.0165775}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 744, "y": 359}, "vk": "default", "time": 1604376115.0285783}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 744, "y": 361}, "vk": "default", "time": 1604376115.0405788}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 745, "y": 362}, "vk": "default", "time": 1604376115.0445793}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 745, "y": 363}, "vk": "default", "time": 1604376115.0565798}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 745, "y": 363}, "vk": "default", "time": 1604376115.0645804}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 746, "y": 365}, "vk": "default", "time": 1604376115.076581}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 746, "y": 365}, "vk": "default", "time": 1604376115.0885816}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 747, "y": 365}, "vk": "default", "time": 1604376115.092582}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 747, "y": 366}, "vk": "default", "time": 1604376115.1245837}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 747, "y": 366}, "vk": "default", "time": 1604376115.1365845}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 747, "y": 367}, "vk": "default", "time": 1604376115.1525853}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 747, "y": 368}, "vk": "default", "time": 1604376115.164586}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 747, "y": 368}, "vk": "default", "time": 1604376115.1725864}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 747, "y": 368}, "vk": "default", "time": 1604376115.1845872}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 748, "y": 369}, "vk": "default", "time": 1604376115.2205894}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 748, "y": 369}, "vk": "default", "time": 1604376115.2365901}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 748, "y": 369}, "vk": "default", "time": 1604376115.2845929}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 748, "y": 370}, "vk": "default", "time": 1604376115.2965937}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 749, "y": 370}, "vk": "default", "time": 1604376115.3605971}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 750, "y": 370}, "vk": "default", "time": 1604376115.3885987}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 750, "y": 371}, "vk": "default", "time": 1604376115.392599}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 750, "y": 372}, "vk": "default", "time": 1604376115.4126003}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 751, "y": 372}, "vk": "default", "time": 1604376115.4246008}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 751, "y": 372}, "vk": "default", "time": 1604376115.4566026}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 751, "y": 373}, "vk": "default", "time": 1604376115.4726036}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 752, "y": 373}, "vk": "default", "time": 1604376115.516606}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 752, "y": 374}, "vk": "default", "time": 1604376115.5526083}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 753, "y": 374}, "vk": "default", "time": 1604376115.600611}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 753, "y": 375}, "vk": "default", "time": 1604376115.6126115}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 753, "y": 375}, "vk": "default", "time": 1604376115.616612}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 754, "y": 375}, "vk": "default", "time": 1604376115.6366131}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 754, "y": 375}, "vk": "default", "time": 1604376116.28465}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 754, "y": 375}, "vk": "default", "time": 1604376116.492662}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 754, "y": 375}, "vk": "default", "time": 1604376116.28465}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 754, "y": 375}, "vk": "default", "time": 1604376116.492662}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 754, "y": 375}, "vk": "default", "time": 1604376116.28465}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 754, "y": 375}, "vk": "default", "time": 1604376116.492662}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604376118.8227952}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604376119.3218238}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604376119.3548257}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604376119.3878276}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604376119.4208295}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604376119.4538314}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 86, "time": 1604376119.462832}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 86, "time": 1604376119.5908394}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604376119.6788442}