{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 475, "y": 327}, "vk": "default", "time": 1604315916.5770822}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 474, "y": 328}, "vk": "default", "time": 1604315916.589083}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 473, "y": 329}, "vk": "default", "time": 1604315916.5930831}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 472, "y": 330}, "vk": "default", "time": 1604315916.605084}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 471, "y": 330}, "vk": "default", "time": 1604315916.6170845}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 471, "y": 331}, "vk": "default", "time": 1604315916.6250849}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 469, "y": 332}, "vk": "default", "time": 1604315916.6370857}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 467, "y": 334}, "vk": "default", "time": 1604315916.6490862}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 464, "y": 334}, "vk": "default", "time": 1604315916.6530864}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 461, "y": 336}, "vk": "default", "time": 1604315916.6650872}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 457, "y": 338}, "vk": "default", "time": 1604315916.6730876}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 454, "y": 339}, "vk": "default", "time": 1604315916.6850882}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 451, "y": 340}, "vk": "default", "time": 1604315916.697089}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 448, "y": 342}, "vk": "default", "time": 1604315916.7010894}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 445, "y": 343}, "vk": "default", "time": 1604315916.7130897}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 442, "y": 344}, "vk": "default", "time": 1604315916.7210903}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 440, "y": 345}, "vk": "default", "time": 1604315916.733091}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 437, "y": 346}, "vk": "default", "time": 1604315916.745092}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 435, "y": 346}, "vk": "default", "time": 1604315916.749092}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 433, "y": 348}, "vk": "default", "time": 1604315916.7610927}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 431, "y": 349}, "vk": "default", "time": 1604315916.7730935}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 429, "y": 349}, "vk": "default", "time": 1604315916.7810938}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 428, "y": 350}, "vk": "default", "time": 1604315916.7930944}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 426, "y": 351}, "vk": "default", "time": 1604315916.7970946}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 426, "y": 352}, "vk": "default", "time": 1604315916.8090954}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 424, "y": 353}, "vk": "default", "time": 1604315916.817096}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 424, "y": 354}, "vk": "default", "time": 1604315916.8290968}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 423, "y": 354}, "vk": "default", "time": 1604315916.841097}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 423, "y": 355}, "vk": "default", "time": 1604315916.8450975}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 421, "y": 356}, "vk": "default", "time": 1604315916.8570983}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 421, "y": 357}, "vk": "default", "time": 1604315916.8650985}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 420, "y": 357}, "vk": "default", "time": 1604315916.8770993}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 420, "y": 358}, "vk": "default", "time": 1604315916.8891}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 418, "y": 358}, "vk": "default", "time": 1604315916.8931003}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 418, "y": 358}, "vk": "default", "time": 1604315916.9051008}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 418, "y": 359}, "vk": "default", "time": 1604315916.9211018}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 417, "y": 359}, "vk": "default", "time": 1604315916.925102}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 417, "y": 360}, "vk": "default", "time": 1604315916.9371026}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 417, "y": 360}, "vk": "default", "time": 1604315916.9411032}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 417, "y": 360}, "vk": "default", "time": 1604315916.9531035}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 416, "y": 360}, "vk": "default", "time": 1604315916.9651043}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 415, "y": 361}, "vk": "default", "time": 1604315916.973105}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 415, "y": 361}, "vk": "default", "time": 1604315916.9851055}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 414, "y": 362}, "vk": "default", "time": 1604315916.9891057}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 414, "y": 362}, "vk": "default", "time": 1604315917.0011065}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 412, "y": 363}, "vk": "default", "time": 1604315917.0131073}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 411, "y": 364}, "vk": "default", "time": 1604315917.0211077}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 409, "y": 365}, "vk": "default", "time": 1604315917.0331082}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 409, "y": 365}, "vk": "default", "time": 1604315917.0411088}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 408, "y": 366}, "vk": "default", "time": 1604315917.0531094}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 407, "y": 366}, "vk": "default", "time": 1604315917.06511}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 407, "y": 366}, "vk": "default", "time": 1604315917.0691102}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 406, "y": 367}, "vk": "default", "time": 1604315917.081111}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 406, "y": 367}, "vk": "default", "time": 1604315917.0891113}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 406, "y": 368}, "vk": "default", "time": 1604315917.1011121}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 405, "y": 368}, "vk": "default", "time": 1604315917.113113}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 404, "y": 370}, "vk": "default", "time": 1604315917.117113}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 402, "y": 371}, "vk": "default", "time": 1604315917.1291137}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 401, "y": 373}, "vk": "default", "time": 1604315917.137114}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 400, "y": 375}, "vk": "default", "time": 1604315917.1491148}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 399, "y": 376}, "vk": "default", "time": 1604315917.1611156}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 397, "y": 377}, "vk": "default", "time": 1604315917.1651158}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 397, "y": 378}, "vk": "default", "time": 1604315917.1771164}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 396, "y": 379}, "vk": "default", "time": 1604315917.1891172}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 396, "y": 379}, "vk": "default", "time": 1604315917.1971178}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 395, "y": 379}, "vk": "default", "time": 1604315917.2091181}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 394, "y": 380}, "vk": "default", "time": 1604315917.2131186}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 394, "y": 381}, "vk": "default", "time": 1604315917.2451205}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 393, "y": 381}, "vk": "default", "time": 1604315917.257121}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 393, "y": 381}, "vk": "default", "time": 1604315917.2611213}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 392, "y": 382}, "vk": "default", "time": 1604315917.273122}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 391, "y": 382}, "vk": "default", "time": 1604315917.2851229}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 391, "y": 382}, "vk": "default", "time": 1604315917.293123}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 390, "y": 383}, "vk": "default", "time": 1604315917.3051238}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 389, "y": 384}, "vk": "default", "time": 1604315917.3171246}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 388, "y": 384}, "vk": "default", "time": 1604315917.3211246}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 388, "y": 385}, "vk": "default", "time": 1604315917.3331254}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 386, "y": 386}, "vk": "default", "time": 1604315917.3531263}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 386, "y": 387}, "vk": "default", "time": 1604315917.365127}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 385, "y": 388}, "vk": "default", "time": 1604315917.3691275}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 384, "y": 388}, "vk": "default", "time": 1604315917.3811283}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 384, "y": 389}, "vk": "default", "time": 1604315917.3891287}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 383, "y": 389}, "vk": "default", "time": 1604315917.4011292}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 383, "y": 390}, "vk": "default", "time": 1604315917.4051294}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 383, "y": 390}, "vk": "default", "time": 1604315917.4171302}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 383, "y": 390}, "vk": "default", "time": 1604315917.433131}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 382, "y": 390}, "vk": "default", "time": 1604315917.4371312}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 382, "y": 391}, "vk": "default", "time": 1604315917.449132}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 382, "y": 391}, "vk": "default", "time": 1604315917.4611328}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 381, "y": 392}, "vk": "default", "time": 1604315917.4651327}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 380, "y": 392}, "vk": "default", "time": 1604315917.4771335}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 380, "y": 393}, "vk": "default", "time": 1604315917.4851341}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 379, "y": 393}, "vk": "default", "time": 1604315917.497135}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 379, "y": 393}, "vk": "default", "time": 1604315917.5091357}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 379, "y": 394}, "vk": "default", "time": 1604315917.5131357}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 378, "y": 395}, "vk": "default", "time": 1604315917.5331368}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 377, "y": 395}, "vk": "default", "time": 1604315917.5451374}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 377, "y": 395}, "vk": "default", "time": 1604315917.5571382}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 377, "y": 396}, "vk": "default", "time": 1604315917.5651386}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 376, "y": 396}, "vk": "default", "time": 1604315917.5771394}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 376, "y": 396}, "vk": "default", "time": 1604315917.58914}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 374, "y": 397}, "vk": "default", "time": 1604315917.5931401}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 374, "y": 398}, "vk": "default", "time": 1604315917.605141}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 373, "y": 398}, "vk": "default", "time": 1604315917.6131415}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 373, "y": 399}, "vk": "default", "time": 1604315917.625142}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 372, "y": 401}, "vk": "default", "time": 1604315917.637143}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 371, "y": 402}, "vk": "default", "time": 1604315917.641143}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 370, "y": 404}, "vk": "default", "time": 1604315917.653144}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 367, "y": 406}, "vk": "default", "time": 1604315917.6611443}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 366, "y": 407}, "vk": "default", "time": 1604315917.6731448}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 365, "y": 408}, "vk": "default", "time": 1604315917.6851456}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 364, "y": 409}, "vk": "default", "time": 1604315917.6891458}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 363, "y": 412}, "vk": "default", "time": 1604315917.7011464}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 362, "y": 413}, "vk": "default", "time": 1604315917.709147}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 361, "y": 414}, "vk": "default", "time": 1604315917.7211475}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 360, "y": 417}, "vk": "default", "time": 1604315917.7331483}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 359, "y": 418}, "vk": "default", "time": 1604315917.7371485}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 359, "y": 419}, "vk": "default", "time": 1604315917.749149}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 358, "y": 420}, "vk": "default", "time": 1604315917.76115}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 358, "y": 421}, "vk": "default", "time": 1604315917.7691503}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 358, "y": 423}, "vk": "default", "time": 1604315917.781151}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 357, "y": 423}, "vk": "default", "time": 1604315917.7851512}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 356, "y": 425}, "vk": "default", "time": 1604315917.797152}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 356, "y": 425}, "vk": "default", "time": 1604315917.8091526}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 356, "y": 426}, "vk": "default", "time": 1604315917.817153}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 355, "y": 426}, "vk": "default", "time": 1604315917.8291538}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 355, "y": 428}, "vk": "default", "time": 1604315917.833154}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 355, "y": 428}, "vk": "default", "time": 1604315917.8451548}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 355, "y": 429}, "vk": "default", "time": 1604315917.8571553}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 355, "y": 429}, "vk": "default", "time": 1604315917.865156}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 431}, "vk": "default", "time": 1604315917.8771565}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 431}, "vk": "default", "time": 1604315917.889157}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 432}, "vk": "default", "time": 1604315917.8931575}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 432}, "vk": "default", "time": 1604315917.905158}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 433}, "vk": "default", "time": 1604315917.9131587}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 434}, "vk": "default", "time": 1604315917.9251595}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 434}, "vk": "default", "time": 1604315917.93716}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 434}, "vk": "default", "time": 1604315917.9411602}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 435}, "vk": "default", "time": 1604315917.9611611}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 435}, "vk": "default", "time": 1604315917.973162}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 436}, "vk": "default", "time": 1604315917.989163}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 436}, "vk": "default", "time": 1604315918.0011635}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 437}, "vk": "default", "time": 1604315918.021165}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 438}, "vk": "default", "time": 1604315918.0331652}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 438}, "vk": "default", "time": 1604315918.0371659}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 439}, "vk": "default", "time": 1604315918.0571668}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 439}, "vk": "default", "time": 1604315918.0691676}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 440}, "vk": "default", "time": 1604315918.0811682}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 441}, "vk": "default", "time": 1604315918.0891685}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 441}, "vk": "default", "time": 1604315918.1011693}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 442}, "vk": "default", "time": 1604315918.1051698}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 443}, "vk": "default", "time": 1604315918.11717}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 443}, "vk": "default", "time": 1604315918.129171}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 444}, "vk": "default", "time": 1604315918.1371715}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 353, "y": 445}, "vk": "default", "time": 1604315918.1491723}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 446}, "vk": "default", "time": 1604315918.1611726}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 446}, "vk": "default", "time": 1604315918.165173}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 447}, "vk": "default", "time": 1604315918.1771739}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 447}, "vk": "default", "time": 1604315918.201175}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 354, "y": 448}, "vk": "default", "time": 1604315918.2131758}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 355, "y": 448}, "vk": "default", "time": 1604315918.233177}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 355, "y": 448}, "vk": "default", "time": 1604315918.273179}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 355, "y": 448}, "vk": "default", "time": 1604315918.6972034}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 355, "y": 448}, "vk": "default", "time": 1604315918.901215}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 355, "y": 448}, "vk": "default", "time": 1604315918.6972034}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 355, "y": 448}, "vk": "default", "time": 1604315918.901215}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 345, "y": 444}, "vk": "default", "time": 1604317555.7411785}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 345, "y": 444}, "vk": "default", "time": 1604317555.9491904}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604317557.8032966}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604317558.3033252}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604317558.3363268}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604317558.369329}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604317558.4023309}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604317558.4353325}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604317558.4683347}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604317558.5013366}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604317558.5343382}
{"name": "keyboard", "event": "press", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 86, "time": 1604317558.547339}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 86, "time": 1604317558.6593454}
{"name": "keyboard", "event": "release", "target": "default", "action": "default", "location": {"x": "0", "y": "0"}, "vk": 162, "time": 1604317559.1473732}